### PR TITLE
Table baking changes, tailored to [App]Table.

### PR DESCRIPTION
**Pull request by beporter**
Baking a Table from the theme will produce a class that assumes a parent [App]Table is available. This is tailored to complement the `src/Model/Table/Table.php` that ships with the Loadsys Skeleton by suppressing "conventional" initialization code provided in that common parent class.

This includes using a UUID `id` field as the default primary key, and assuming that tables include created, modified, creator_id and modifier_id fields.

### CODE REVIEW

**Comment by beporter** [comment]
I think this is ready to go. I haven't tested the space -> tab fixes in all cases though.

**Comment by justinyost** [comment]
I added some docs about the Table classes.

**Comment by justinyost** [comment]
Otherwise :+1:

**Comment by beporter** [comment]
Ooo, that's good thinking! I'm going to expand it into the start of a "what's different" section intended to call out what you're getting beyond the core's bake templates, if you don't mind.

**Pull request merged**
